name: 🚀 Deploy Vite front to REG.RU

on:
  push:
    branches: [ main ]    # деплой только при пуше в основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Получаем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Node.js 20
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: npm ci || npm i

      # 4. Собираем проект Vite
      - name: Build project
        run: npm run build

      # 5. Добавляем .htaccess в dist для SPA и HTTPS
      - name: Add .htaccess to dist
        run: |
          cat > dist/.htaccess << 'EOF'
          # Включаем сжатие
          <IfModule mod_deflate.c>
            AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript application/json
          </IfModule>

          # Принудительное перенаправление на HTTPS и без www
          RewriteEngine On
          RewriteCond %{HTTPS} off [OR]
          RewriteCond %{HTTP_HOST} ^www\.psytalk\.pro [NC]
          RewriteRule ^(.*)$ https://psytalk.pro/$1 [L,R=301]

          # SPA fallback — чтобы React/Vue маршруты работали
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.html [L]

          # Отключаем кэш для HTML
          <IfModule mod_headers.c>
            <FilesMatch "\.html$">
              Header set Cache-Control "no-cache, no-store, must-revalidate"
              Header set Pragma "no-cache"
              Header set Expires "0"
            </FilesMatch>
          </IfModule>
          EOF

      # 6. Заливаем на хостинг REG.RU через FTP
      - name: Upload via FTP to REG.RU
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./dist/           # куда билдит Vite
          server-dir: /www/psytalk.pro/ # абсолютный путь на сервере
          dangerous-clean-slate: true  # чистит только dist, а не API
          log-level: verbose
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/*.map
            api/**
            *.php
            *.json
            *.md
